### ISSUE TITLE
Update templates for pull requests

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#10]
We still have the old Akka for templates when issues/pull requests are made (see https://github.com/apache/incubator-pekko/tree/main/.github/ISSUE_TEMPLATE), should remove/replace them as necessary.

**Comment by naosense** [comment]
This seems easy to me, just replace repo name and urls?

**Comment by mdedetrich** [comment]
We may want to improve/change the templates later but initially I see no problem in just replacing repo name and urls so its not mentioning Akka or its repos.

**Comment by danischroeter** [comment]
Resolved with #14
