### ISSUE TITLE
in pom files, set name to have 'Apache Pekko ...'

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#1006]
Our poms are generated by sbt and the name in the pom closely matches the artifactId 

https://repo1.maven.org/maven2/org/apache/pekko/pekko-stream_3/1.0.2/pekko-stream_3-1.0.2.pom

See name=pekko-stream, artifactId=pekko-stream_3

We only set the name in sbt but if we change it, it affects the artifactId. We need to keep the artifactId as is.

But for this pom, we should have name=Apache Pekko Stream (or something like that - Apache Pekko bit is the key).

Requirement comes in https://lists.apache.org/thread/wmp9g94fo2yb4tsg238467d6hx72dbml

Liable to become something that can block our releases and graduation to be a TLP.

I have tried a few sbt changes but nothing that gets the results that we need.

**Comment by He-Pin** [comment]
Do you mean the `<name>pekko-stream</name>` should be `<name>apache-pekko-stream</name>`？

**Comment by pjfanning** [comment]
artifactId must stay as `pekko-stream_3` but the name should be `Apache Pekko Stream`

**Comment by laglangyue** [comment]
I just gave it a try for demo project, it's ok, I am preparing a PR for pekko
···
    publishM2Configuration := publishM2Configuration.value
      .withOverwrite(true)
      .withPublishMavenStyle(true),
      // rename module
    makePomConfiguration := makePomConfiguration.value.withModuleInfo(
      makePomConfiguration.value.moduleInfo.get.withNameFormal("apache")
    )
···

**Comment by mdedetrich** [comment]
@laglangyue I would hold off a bit as we are trying to verify if we actually need to do this, @pjfanning Has more details.

If we do end up needing to do this we will also likely end up creating an abstraction in https://github.com/pjfanning/sbt-pekko-build

**Comment by laglangyue** [comment]
> @laglangyue I would hold off a bit as we are trying to verify if we actually need to do this, @pjfanning Has more details.
> 
> If we do end up needing to do this we will also likely end up creating an abstraction in https://github.com/pjfanning/sbt-pekko-build

okey, waitting for this

**Comment by pjfanning** [comment]
changes made
