### ISSUE TITLE
Feature request: AutoCloseable shortcuts

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#1044]
Motivation:
Pekko has mapwithResource now, would be better to support AutoCloseable in Java/Scala dsl too.
refs: https://github.com/reactor/reactor-core/issues/3333

**Comment by injae-kim** [comment]
Can you assign this issue to me? I'll create PR tomorrow~! 🙇

**Comment by He-Pin** [comment]
> Can you assign this issue to me? I'll create PR tomorrow~! 🙇

Thank you, I love it because I use Java everyday

**Comment by mdedetrich** [comment]
We should discuss this properly because supporting cancellation of resources properly is very difficult to get right

**Comment by injae-kim** [comment]
> https://github.com/reactor/reactor-core/pull/3704 Add AutoCloseable shourtcut on Flux#using, Mono#using

```java
	public static <T, D extends AutoCloseable> Flux<T> using(Callable<D> resourceSupplier,
			Function<? super D, ? extends Publisher<? extends T>> sourceSupplier) {
		return using(resourceSupplier, sourceSupplier, AUTO_CLOSE, true);
	}

	static final Consumer<? super AutoCloseable> AUTO_CLOSE = resource -> {
		try {
			resource.close(); //👈 simply close the autocloseable
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	};
```
 Hi @mdedetrich ! On above PR on reactor, I use `<D extends AutoCloseable>` to support only `AutoCloseable` shortcut.
and simply close it cause we usually think that it's okay to close `AutoCloseable`.

WDYT? you mean we should handle or provide a way to user when `autoCloseable.close()` throw exception?

**Comment by He-Pin** [comment]
@injae-kim the `using` is something like `mapWithResource` in pekko or `unfoldResource`, both method need a user to close the resource explicitly. If think if we support this, then there will be an overload method where the `close: () => Unit` is not needed.

**Comment by injae-kim** [comment]
> then there will be an `overload method` where the close: () => Unit is not needed.

aha~ then I'll create PR in this way. let's discuss more details about `cancellation of resources` on PR~! thanks!

**Comment by He-Pin** [comment]
Nice contribution, but pekko-stream and Reactor-core work in a different way, and I'm using both simultaneously in one app, there is some test code, you can read from the java dsl tests, and thank you for your interest.

**Comment by pjfanning** [comment]
this is not under consideration for 1.1.0-M1 and therefore PRs for this feature should be merged yet

if we decide to bring this into consideration for 1.1.0-M1, it will delay it

**Comment by He-Pin** [comment]
It's not in 1.1.0-m1  depends on the status, may be in 1.2.x
