### ISSUE TITLE
Renaming the akka package

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#11]
We need to rename the package from `akka` to either `pekko` or `org.apache.pekko` (this is still being decided). One thing to note is that this will break some tests, i.e. https://github.com/apache/incubator-pekko/blob/6680c47dcc2305906a44d7794081682211d7ee0b/akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala#L983-L995 is dependant on the fully qualified class name so it will also need to be updated when the package changes (there may be other examples of this as well).

**Comment by pjfanning** [comment]
I could be wrong but the mima checks for binary compatibility will likely be meaningless once we change the package names. Maybe we should be pre-emptive and remove the mima checks. If removed, they will obviously need to be reinstated after the first Pekko release.

**Comment by mdedetrich** [comment]
This is indeed correct, the easiest way to resolve this would be to disable the mima package.

**Comment by mdedetrich** [comment]
Since the discussion around the package name has been resolved on the mailing list I am starting to work on this now.

**Comment by pjfanning** [comment]
This is done
