### ISSUE TITLE
1.0.x branch has an empty `publish-1.0-nightly` workflow

### ISSUE THREAD

**Issue by raboof** [apache/incubator-pekko#1109]
Seems to have been introduced in #631 /cc @mdedetrich

**Comment by pjfanning** [comment]
We should just delete the empty file. We run the job from the main branch - the yml has a `ref: 1.0.x` in its checkout.

**Comment by mdedetrich** [comment]
Yeah that appears to be an accident

**Comment by pjfanning** [comment]
Fix merged
