### ISSUE TITLE
link validator fails due to changed url

### ISSUE THREAD

**Issue by nvollmar** [apache/incubator-pekko#1138]
Url `opensource.org/licenses/BSD-3-Clause` changed to `opensource.org/blog/license/bsd-3-clause`

**Comment by raboof** [comment]
Are we sure that was intentional? That doesn't seem like an improvement and perhaps something they'll rollback?

**Comment by nvollmar** [comment]
Not sure, at least it changed for all licenses: https://opensource.org/licenses

**Comment by raboof** [comment]
asked on https://merveilles.town/@raboof/111974245965562026

**Comment by nvollmar** [comment]
I will open an issue on https://github.com/OpenSourceOrg/dotOrg maybe we get an answer there

**Comment by raboof** [comment]
a found it at https://github.com/OpenSourceOrg/dotOrg/issues/60, great

**Comment by nvollmar** [comment]
They will revert back to the original URL
