### ISSUE TITLE
ActorSystem start code has ref to Akka

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#115]
```
ManifestInfo(this).checkSameVersion("Akka", allModules, logWarning = true)
```

Need to work out what to replace this with

**Comment by kw217** [comment]
As far as I can see this `$productName` is just used in the error string `"You are using version $highestVersion of $productName, but..."`, so we can safely change all occurrences to `"Pekko"`.

https://github.com/apache/incubator-pekko/blob/4ac0f00a477873965ee7d52e16faefb1de91fe3a/actor/src/main/scala/org/apache/pekko/util/ManifestInfo.scala#L102

**Comment by kw217** [comment]
Though this does raise the question of what "older" means. Do we plan to release Pekko at `1.0.0` or `2.6.x`? If the former, we will need to tweak code like this to be a bit smarter.

**Comment by pjfanning** [comment]
> Though this does raise the question of what "older" means. Do we plan to release Pekko at `1.0.0` or `2.6.x`? If the former, we will need to tweak code like this to be a bit smarter.

It will be pekko 1.0.0. Why does this matter? Pekko versions will go up - pekko and akka are unrelated - different packages and jars - if someone has akka and pekko on their classpath, they should not interfere with each other.

**Comment by kw217** [comment]
Ah good point - in which case you'll want to remove most of the content of this list then:

https://github.com/apache/incubator-pekko/blob/main/actor/src/main/scala/org/apache/pekko/util/ManifestInfo.scala#L46

**Comment by pjfanning** [comment]
this is done
