### ISSUE TITLE
link validator: AbstractFunction2

### ISSUE THREAD

**Issue by raboof** [apache/incubator-pekko#1158]
the link validator for PRs is failing with:
```
## HTTP failure response
`[https://www.scala-lang.org/api/2.13.13/scala/runtime/AbstractFunction2.html`](https://www.scala-lang.org/api/2.13.13/scala/runtime/AbstractFunction2.html%60) status 404 Not Found
 - ../../../../../target/scala-2.13/unidoc/org/apache/pekko/cluster/index.html
 - ../../../../../target/scala-2.13/unidoc/org/apache/pekko/remote/index.html
``````
... it seems this problem also exists on the main branch. Did scala-lang change or did we miss it in a recent PR?

**Comment by pjfanning** [comment]
We've had to add link validator excludes for this in a few places.

**Comment by pjfanning** [comment]
@raboof see https://github.com/apache/incubator-pekko/blob/main/scripts/link-validator.conf#L64

Looks like we need to upgrade the URLs to have 2.13.13 or find a way not to hardcode the version in the URL.

**Comment by pjfanning** [comment]
I think this is fixed
