### ISSUE TITLE
pekko-cluster shell script needs to remove akka refs

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#116]
https://github.com/apache/incubator-pekko/blob/main/cluster/jmx-client/pekko-cluster

* Not just superficial println text
* also JMX and other `akka` refs in the script

**Comment by dnychennnn** [comment]
Hi,

here's the [PR](https://github.com/apache/incubator-pekko/pull/127) for the fix.

Best,
Denny

**Comment by pjfanning** [comment]
PR is merged- https://github.com/apache/incubator-pekko/pull/127
