### ISSUE TITLE
remove the Akka-Enhancements/Pekko-Enhancements docs

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#122]
These docs are Lightbend specific.

https://lists.apache.org/thread/8orjtlx2w42y3j45pswmf9nbtf64gp77

**Comment by dnychennnn** [comment]
Hi @pjfanning,

I'd like to start with this in #126.

Regards,
Denny

**Comment by pjfanning** [comment]
thanks @dnychennnn - I'll close this
