### ISSUE TITLE
docs: fix up references to lightbend portal

### ISSUE THREAD

**Issue by Seetaramayya** [apache/incubator-pekko#124]
We need to produce a Pekko equivalent for `samples` or `start` guides and fix up the docs references to  https://developer.lightbend.com/start/?group=

**Comment by pjfanning** [comment]
#243 is open for the samples

**Comment by sam-byng** [comment]
This has been done in samples as part of #243 . (https://github.com/apache/incubator-pekko-samples/search?q=lightbend , remaining references are in legal docs / non akka dependencies)

Remaining here for samples are: https://github.com/apache/incubator-pekko-samples/blob/74f578c9cd4c0e13d0450ed1fe14ced8d1d325e2/pekko-sample-persistence-dc-java/src/main/resources/application.conf and https://github.com/apache/incubator-pekko-samples/blob/74f578c9cd4c0e13d0450ed1fe14ced8d1d325e2/pekko-sample-persistence-dc-scala/src/main/resources/application.conf

**Comment by pjfanning** [comment]
@sam-byng could you create an issue for those comments in https://github.com/apache/incubator-pekko-samples/issues

**Comment by sam-byng** [comment]
i'll look at fixing those now.

**Comment by sam-byng** [comment]
Since that's done. On "start guides" , is this card referencing anything that is not already covered by:

https://github.com/apache/incubator-pekko/issues/123
and
https://github.com/apache/incubator-pekko/issues/244

If not then I propose closing this card.

**Comment by pjfanning** [comment]
sure - #123, #244 and #284 cover the remaining work
