### ISSUE TITLE
Publish artifacts using JDK 1.8 or remove sbt JDK 1.8 check?

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#132]
So I noticed that when publishing Pekko we are doing so using JDK 11. While there is no problem with this, at the same time the current sbt build will refuse to load with a JDK that is newer than 1.8.

We should either pubilsh using JDK 1.8 (at least for the 1.0.x branch) or just remove the sbt check?

**Comment by mdedetrich** [comment]
So I spoke with @raboof at FOSDEM, and the situation with pekko build is quite interesting and complicated. While building documentation only works with JDK 11 (as has been commented in the various github actions workflows), the core build/artifacts of Pekko needs to be built with JDK 1.8.

While typically one would use `source`/`target` tags (such as https://github.com/pjfanning/sbt-source-dist/blob/main/build.sbt#L9), specifically in the case of Pekko this doesn't work because while the `source`/`target` flags force javac to produce the relevant targeted bytecode, it doesn't account for JVM standard library changes and apparently there was some ABI incompatible standard library changes from JDK 1.8 to JDK 11.

**Comment by raboof** [comment]
:wave: it was good to meet in person!

I would definitely recommend compiling with JDK11 or later, to unlock some things related to `java.util.concurrent` and JFR, even if for 'the rest' of the artifacts we support running on Java 8.

Indeed normally you'd just build with JDK11 and target Java 8, but because of some JVM standard library changes, for some classes (notably `EnvelopeBuffer`) this isn't sufficient, and you need to provide a reference to the JDK8 runtime library. Additionally, I think some of the `sun.misc.Unsafe` usage should still be removed before this is possible.

So best in the short run would be to build with JDK11, but have JDK8 available on the build machine as well. I think on most systems this should be auto-detected (and throw an error when it is not found, in which case you can point a `JAVA_8_HOME` environment variable to it).

More details at https://github.com/apache/incubator-pekko/blob/main/project/JdkOptions.scala#L60-L67 and https://github.com/apache/incubator-pekko/blob/main/project/JdkOptions.scala#L77-L79.

**Comment by mdedetrich** [comment]
> So best in the short run would be to build with JDK11, but have JDK8 available on the build machine as well. I think on most systems this should be auto-detected (and throw an error when it is not found, in which case you can point a JAVA_8_HOME environment variable to it).

So just to clarify what is going on, it appears that to properly build Pekko (and by build I mean JVM artifacts which are shipped to Maven repo) we need a machine which

1. Has a JDK 8 installation available which `JAVA_8_HOME` needs to point to
2. Also has a JDK 11 installation available which I presume can have the standard installation (i.e. `JAVA_HOME`) point to this. Necessary for docs and `java.util.concurrent`.

From a quick look at the code it does appear to automatically handle which artifacts need to compiled with which JDK. In any case the reason why I am asking this is that it needs to be documented as part of the release process (and also checked/improved/modified) because a proper ASF release needs to be done on a release managers machine, not CI.

**Comment by raboof** [comment]
Yes, that looks accurate.

> the reason why I am asking this is that it needs to be documented as part of the release process (and also checked/improved/modified) because a proper ASF release needs to be done on a release managers machine, not CI.

It might be interesting to know it might be OK to create ASF releases from CI when certain conditions are met, something like:

- project has reproducible builds for source and binary artifacts
- RM creates tag
- CI system builds RC, signs it with a CI specific key and deploys it to staging
- PMC members review the release which includes building and confirming that source and binary artifacts are as expected (identical to those built by CI)
- PMC members VOTE
- RM promotes RC if vote passes

As you can see this hinges on having reproducible builds for Pekko - which might be a good thing to have in any case, but premature to require for the release? I've done some work towards that in the past, so it might be close, but I'm not sure it's currently complete.

(more context on the members list at https://lists.apache.org/thread/dytplxdj7cy545oxcvgl2wjombj3gbmc - we might want to clarify https://www.apache.org/legal/release-policy.html#owned-controlled-hardware further at some point)

**Comment by mdedetrich** [comment]
Answered in https://github.com/apache/incubator-pekko/issues/130#issuecomment-1420723915 since its a more relevant thread

**Comment by jrudolph** [comment]
> Indeed normally you'd just build with JDK11 and target Java 8, but because of some JVM standard library changes, for some classes (notably `EnvelopeBuffer`) this isn't sufficient, and you need to provide a reference to the JDK8 runtime library. Additionally, I think some of the `sun.misc.Unsafe` usage should still be removed before this is possible.

We should check if that is even still correct, that sounds like a bug in one version of JDK 11 that might have been fixed in the meantime...

**Comment by mdedetrich** [comment]
> We should check if that is even still correct, that sounds like a bug in one version of JDK 11 that might have been fixed in the meantime...

This would be nice in the sense that if has been fixed then there is less of a need to create a `Dockerfile` so we can setup a proper build environment for a release manager

**Comment by jrudolph** [comment]
I just checked and at least the Unsafe usage would have to be fixed. Additionally, just verifying that one issue might not be enough to validate that there might be other incompatibilities with JDK 8, so I guess we should keep it like this for now...

**Comment by jrudolph** [comment]
Do we understand how this is currently working on GHA? We only install JDK 11 but JDK 8 is automatically available on the `ubuntu-20.04` of GHA?

**Comment by spangaer** [comment]
Not sure whether that makes it magically work, but yes:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java
(4 JDKs as it even packs Graal it seems)

**Comment by mdedetrich** [comment]
> Not sure whether that makes it magically work, but yes: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java (4 JDKs as it even packs Graal it seems)

Thanks but the environment variable is different here than what pekkos sbt seems to be checking? From https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java it says `JAVA_HOME_8_X64` but the sbt build checks for `JAVA_HOME_8`?

**Comment by raboof** [comment]
If `JAVA_8_HOME` is not set, the build [consults](https://github.com/apache/incubator-pekko/blob/main/project/JdkOptions.scala#L92) the sbt [fullJavaHomes](https://github.com/sbt/sbt/blob/973cd63e0b6bfe0d06d364f314f391a08a77d38b/main/src/main/scala/sbt/Defaults.scala#L206), which among other sources [auto-detects Java from common distribution paths](https://github.com/sbt/sbt/blob/973cd63e0b6bfe0d06d364f314f391a08a77d38b/main/src/main/scala/sbt/internal/CrossJava.scala#L485)

**Comment by mdedetrich** [comment]
> If `JAVA_8_HOME` is not set, the build [consults](https://github.com/apache/incubator-pekko/blob/main/project/JdkOptions.scala#L92) the sbt [fullJavaHomes](https://github.com/sbt/sbt/blob/973cd63e0b6bfe0d06d364f314f391a08a77d38b/main/src/main/scala/sbt/Defaults.scala#L206), which among other sources [auto-detects Java from common distribution paths](https://github.com/sbt/sbt/blob/973cd63e0b6bfe0d06d364f314f391a08a77d38b/main/src/main/scala/sbt/internal/CrossJava.scala#L485)

Thanks.

The good news is that then the CI building pekko-core is then a non issue so snapshots shouldn't have problems related to this thread. If I understand correctly they also happen to offer equivalent docker images (see https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#cached-docker-images) which then makes the just a lot easier for a release manager.

**Comment by mdedetrich** [comment]
I am closing this since all questions have been answered, i.e. we are going to release with JDK 8 support.
