### ISSUE TITLE
add license headers to markdown files

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#134]
ASF generally prefer that all files have Apache license headers - not just the source files. 

There are js and html files in the docs dir too - these probably would be better with license headers too.

Use of `sbt-header` to check for and automate the adding of license headers is preferred.

sbt-paradox may work differently from Github.

Github supports:
```
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  license agreements; and to You under the Apache License, version 2.0:
 
    https://www.apache.org/licenses/LICENSE-2.0

  This file is part of the Apache Pekko project, derived from Akka.
-->
```

It maybe better to start with `<!---` - some tools document it this way.

**Comment by pjfanning** [comment]
I've done a little experimentation. It seems like Paradox prefers `<!---` (ending with `-->`).

It seems like we may not be able to the license header at the start of every files, Paradox expects certain features to appear right at the start of the .md file so we would need in some cases to put the license header after that intro.

See this example in the Druid build - https://github.com/apache/druid/edit/master/docs/operations/use_sbt_to_build_fat_jar.md

This section only works properly if it appears at the start of the file.
```
---
id: use_sbt_to_build_fat_jar
title: "Content for build.sbt"
---
```

I have hit trouble with adding the license header to some of the Pekko .md files which causes sbt-paradox to fail. I haven't had time to debug all the issues yet.

**Comment by mdedetrich** [comment]
I would presume that similar to conf files we can use the SPDIF license format?

**Comment by pjfanning** [comment]
@mdedetrich this may not be needed based on https://issues.apache.org/jira/browse/LEGAL-634 comments

**Comment by mdedetrich** [comment]
Okay let's close the issue once it's clarified then.
