### ISSUE TITLE
fix issue with license/notice in pekko-protobuf-v3 jar

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#140]
* this jar is built using sbt-assembly and it basically shades classes from protobuf-java v3
* the existing project/MetaInfLicenseNoticeCopy.scala works for jars that we build from compiled source and resource files but does not work with sbt-assembly built jars
* sbt-assembly may have an option to add artbitrary files to the output jar but I haven't found it
* one possible solution is to build a local jar as part of the pekko build that just contains the license and notice files in its META-INF dir and let sbt-assembly merge it and the shaded contents of protobuf-java v3
* a more radical solution might be to drop the pekko-protobuf-v3 jar altogether and just use the akka 2.6 one (likewise for the pekko-protobuf jar - this one is similar but built differently, we already have its source copied to our repo and build it like a normal jar)

**Comment by mdedetrich** [comment]
> sbt-assembly may have an option to add artbitrary files to the output jar but I haven't found it

I just had a look and also couldn't find it but I think this might be a considered a reasonable option and upstream may be open to it. Ill make an issue on it

**Comment by mdedetrich** [comment]
Another option, since jar files follow the zip standard it shouldn't be too hard to just decompress the Jar file manually, add in the LICENSE/NOTICE (and any other necessary files) and then just recreate the jar. Would be a bit annoying as a workaround but it should be possible.

**Comment by mdedetrich** [comment]
I will try and look into this on the weekend

**Comment by mdedetrich** [comment]
So I made an issue on sbt-assembly at https://github.com/sbt/sbt-assembly/issues/491 some time ago and didn't get a response, I might try programming the solution and pinging the stakeholders. 

If that doesn't end up working out (we can define a cutoff) then we can manually do the zip workaround I mentioned before.

**Comment by mdedetrich** [comment]
So I made a draft PR for sbt-assembly at https://github.com/sbt/sbt-assembly/pull/493 but @jrudolph is implying that it may not be necessary and that sbt-assembly should work with sbt's standard mechanism for resources.
