### ISSUE TITLE
Complete Pekko doc updates

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#145]
Some work is done but there is plenty more to do:
* [pekko custom sbt-paradox](https://github.com/apache/incubator-pekko-sbt-paradox) (tentatively @jrudolph)
   * https://github.com/apache/incubator-pekko/issues/92 
* continuing work on updating docs (markdown files)
   * removing Akka/Lightbend specific docs (sometimes by linking to the Akka doc)
   * links and other akka references

**Comment by pjfanning** [comment]
linked to #98

**Comment by Claudenw** [comment]
What is the status here ?  is there a list of things that need to be done to close this issue?  or a tool that can be used to find all the places that need to be checked?

**Comment by pjfanning** [comment]
Only humans who check the docs - that's all we have.

This is largely done. I'll close this and let humans report any issues that they find - as new issues.
