### ISSUE TITLE
investigate pekko-osgi test artifact blueprint.xml

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#186]
```
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:akka="http://akka.io/xmlns/blueprint/v1.0.0">

    <akka:actor-system name="BlueprintSystem" />

    <akka:actor-system name="BlueprintSystemWithConfig">
        <akka:config>
            some.config {
              key=value
            }
        </akka:config>
    </akka:actor-system>
</blueprint>
```

Can this just be modified to use `pekko` instead of `akka`?

**Comment by spangaer** [comment]
Now my xml tags are a bit rusty, but if you update the URL it seems fine
https://stackoverflow.com/a/11602530/574370

Merely a means of namespacing XML tags not to collide with those of OSGi.
(matter of updating the parsing code of course)

**Comment by pjfanning** [comment]
Sometimes the URI matters because it may relate to an XML schema - but changing the URI appears to break no tests.

**Comment by pjfanning** [comment]
https://github.com/apache/incubator-pekko/pull/201 was merged
