### ISSUE TITLE
Enable github status checks for CI

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#23]
Currently its possible to merge a PR even if the status checks fail or even in the small span of time before they get triggered. Now that we have CI running properly, we should update the `Require status checks to pass before merging` under `Branch Protection Rules` for the main branch so that people cannot easily merge PR's if one of the status checks fail.

@pjfanning I am not sure if this is to be done directly under github actions or whether it needs to be organised with an INFRA ticket/`.asf.yaml`?

**Comment by pjfanning** [comment]
This is something we will want to implement. I'm not yet sure that we have enough stability in the dev pipelines though.

In the end of the day, we are months away from any releases, anything that sneaks into the main branch can be fixed - this will hopefully be rare.

**Comment by spangaer** [comment]
Explicitly having to name the status checks for that feature to do anything meaningful, is an additional complication.

**Comment by mdedetrich** [comment]
> This is something we will want to implement. I'm not yet sure that we have enough stability in the dev pipelines though.

So we don't have to enable all of the status checks however there are ones that make sense to enable even now, i.e.

* `Scalafmt / Code is formatted (pull_request)`
* `Pull Requests / Check / Headers (pull_request)`

And all of the compile ones (I don't think we ever want to merge code that actually can't compile)

Also do note that even with status checks enabled you can bypass them, you just need to write permissions to the repo which in the current case is PMC members

> Explicitly having to name the status checks for that feature to do anything meaningful, is an additional complication.

I don't know what you mean, if you are talking about the logistics of enabling them then its really quite trivial, you get a dropdown of past checks that have triggered (which we are already at this point in time) and you just select the ones that you want to enable.

**Comment by spangaer** [comment]
From UI it's not very complicated, from API there's a couple of pitfalls, which I assume will extrapolate to this asf.yml file.

**Comment by mdedetrich** [comment]
> From UI it's not very complicated, from API there's a couple of pitfalls, which I assume will extrapolate to this asf.yml file.

Ah thats what you mean, I assume if there is an example Apache project with a configuration it shouldn't be too hard to figure out.

**Comment by mdedetrich** [comment]
I would say it's still currently being worked on (as in I am going through each pekko git report and putting the checks in)
