### ISSUE TITLE
license: acknowledge use of codahale code

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#232]
See https://github.com/apache/incubator-pekko/blob/4a36d2600e7a5cb311418a7ef98ca7899c4a8f4d/cluster/src/main/scala/org/apache/pekko/cluster/VectorClock.scala#L24

This needs some research. We may need to track down original class to see VectorClock.scala is based on porting the code to Scala or if the class was written based on a high level understanding of the original code.

**Comment by justinmclean** [comment]
HI,
> I checked the code and this comment have been in the code since 2012. It appears to be based on https://github.com/codahale/vlock <https://github.com/codahale/vlock>. That code has no license or headers specified. I think we can skip making any changes in Pekko to acknowledge this better.
> 

Which probably means we need to get permission from the author (or copyright holder) to use it.

Justin

**Comment by codahale** [comment]
You could have just mentioned me here instead of opening an issue on a random project of mine. Or, like, emailed me at the email address associated with every one of my commits on GitHub.

I hereby grant you permission to use that code under any OSS license of your choosing.

**Comment by pjfanning** [comment]
> You could have just mentioned me here instead of opening an issue on a random project of mine. Or, like, emailed me at the email address associated with every one of my commits on GitHub.
> 
> I hereby grant you permission to use that code under any OSS license of your choosing.

We will use an Apache License, v2.0. Thanks @codahale

**Comment by pjfanning** [comment]
#272 merged
