### ISSUE TITLE
other source files to add licenses to

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#238]
Follow up to https://github.com/apache/incubator-pekko/issues/134

* again sbt-header usage is preferred to automate header checks and creation
* #134 covers markdown files in the docs dir (used to generate the web site)
* we also have shell scripts, sbt files, github yml files - probably more types
* we may not need to put headers on absolutely everything

**Comment by sam-byng** [comment]
So it seems that discussion in [LEGAL-634](https://issues.apache.org/jira/browse/LEGAL-634) has resulted in the following position for .md files:

> - We don't adjust the Pekko copy of the markdown files to add any Apache headers
> - The HTML pages that we deploy to the Pekko web site, will have a Lightbend copyright in the page footers or perhaps no copyright at all 

I.e. Copyrights will be whatever was there for the akka docs.

Correct?

**Next questions**: 
1. For the other files in this repo (sbt files, shell scripts, github yml, ...) does the following sound ok?

Proposal: To all of these file types, add the same header that resulted from discussions in [LEGAL-626](https://issues.apache.org/jira/browse/LEGAL-626).
If the file has already got a Lightbend header, then this will go above that. If the file has no copyright header at the moment, then this will be the first license header to be added.

```
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * license agreements; and to You under the Apache License, version 2.0:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * This file is part of the Pekko project, derived from Akka.
 */
```

If possible, do this using the `sbt-header` scala code.

2. Does this card cover updating the other pekko modules going into 1.0.0? (pekko-samples, pekko-sbt-paradox, pekko-http, pekko-platform guide)

3. The discussion in  [LEGAL-626](https://issues.apache.org/jira/browse/LEGAL-626?focusedCommentId=17648595&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17648595) resolved to use `This file is part of the Apache Pekko project, **which is** derived from Akka.` - we didn't do this - does this need a fix?

**Comment by pjfanning** [comment]
* The .md files will be left as is - no ASF licensing
* the license header text is fine - let's leave it as is
* whether to bother adding license headers to more files - maybe - I'm not too pushed - we have the main ones sorted out
* if we do proceed with more - maybe `.sbt` and `.yml`. I would prefer not to touch the shell scripts because there is a risk that they are not well tested in CI.

**Comment by sam-byng** [comment]
Ok, I'm going to leave this for now. Sounds like they're not _must-have_ for 1.0.0 . 

If we change our mind/in future, someone can pick up .sbt (2 files), .yml (~15 files) files and other (conf?/xml?) , and do the same in the other modules.

**Comment by pjfanning** [comment]
I think we can leave this for now. When we vote on the releases, one of the voters may highlight something and we can review that then.

I think anything that does not have an Apache header now falls in 2 categories:
* was written in Akka days and has not been significantly changed by us
* the file is not an important file - it may or may not be nice to have a header, but it is not required to have a header
