### ISSUE TITLE
Update documentation (.MD files)  to remove references to akka and lightbend where appropriate

### ISSUE THREAD

**Issue by Claudenw** [apache/incubator-pekko#28]
Currently the README and CONTRIBUTING files contain references to akka and lightbend.  While it may be correct and proper to reference them as original sources for the code base, other uses seem inappropriate.  This change should removed most of the akka and lightbend phrases from the documentation.

**Comment by softinio** [comment]
The CONTRIBUTING guide references [this](https://www.lightbend.com/contribute/cla) what would replace this?

**Comment by nvollmar** [comment]
We're also going to have to replace the [akka-paradox](https://github.com/akka/akka-paradox) sbt plugin to brand the documentation with Pekko.

Since it doesn't have a license attached we might want to start from scratch with that.

**Comment by softinio** [comment]
> We're also going to have to replace the [akka-paradox](https://github.com/akka/akka-paradox) sbt plugin to brand the documentation with Pekko.
> 
> Since it doesn't have a license attached we might want to start from scratch with that.

At a glance looks like its just [paradox](https://github.com/lightbend/paradox) with a custom theme. Maybe easiest path of resistance is to replace it with [paradox](https://github.com/lightbend/paradox)

**Comment by nvollmar** [comment]
Yep, it is just a custom theme. Short term we could just switch to the basic [sbt-paradox](https://developer.lightbend.com/docs/paradox/current/getting-started.html), but long term we should create our own theme.

**Comment by softinio** [comment]
@nvollmar created a separate issue for the akka-paradox plugin replacement as I thought it can be worked on separately: 

https://github.com/apache/incubator-pekko/issues/32

If no objection happy to start work on it tomorrow.

**Comment by samikrc** [comment]
I would like to work on this issue (doc update) as much as I can. Will raise a PR.
Quick question: are we eventually planning to update the folder names from "akka-*" to "pekko-*" as well?

**Comment by pjfanning** [comment]
I am working on the folder renames

**Comment by samikrc** [comment]
> I am working on the folder renames

Thanks - that is probably listed as another issue then.

**Comment by samikrc** [comment]
Created a PR with updates to markdown files: https://github.com/apache/incubator-pekko/pull/36

**Comment by pjfanning** [comment]
I think this is done. Please reopen if you find specific items in the .md files that need fixing.
