### ISSUE TITLE
Migrate akka k8s samples to pekko

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#286]
Migrate akka k8s samples to pekko

* https://github.com/akka/akka-sample-cluster-kubernetes-scala
* https://github.com/akka/akka-sample-cluster-kubernetes-java

these 2 samples are linked to from the Pekko docs and it would be good to link to Pekko versions instead of Akka versions

**Comment by sam-byng** [comment]
Proposal: Could these be added as directories in https://github.com/apache/incubator-pekko-samples , to avoid creating new git repositories?

**Comment by pjfanning** [comment]
sure - these can be added to incubator-pekko-samples

**Comment by sam-byng** [comment]
i'll do this today

**Comment by pjfanning** [comment]
this is done (I think)

**Comment by sam-byng** [comment]
Correct, thanks
