### ISSUE TITLE
link validator check broken by license-report

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#326]
Not urgent. Just spotted the broken CI job.

https://github.com/apache/incubator-pekko/actions/runs/5042361658

fyi @mdedetrich

**Comment by mdedetrich** [comment]
I just did a quick cursory look and aside from the link validator failing due to docs not being fully fixed (which is expected) it appears to also fail if use non https links, i.e.

```
 * Failure responses found.
 * Non-https URLs found (configure `non-https-accepted` if needed).
Error: Process completed with exit code 255.
```

**Comment by mdedetrich** [comment]
Ah I see the issue now, sbt-license-report is putting links in the report that are derived from the pom fields in the transitive dependencies. Some of those fields are only http, so a low hanging fruit improvement can be enabling http.

**Comment by pjfanning** [comment]
is it possible to get link-validator to skip this file altogether?

Then we can validate only https is used in our main pages.

**Comment by mdedetrich** [comment]
After checking both the example [application.conf](https://github.com/ennru/site-link-validator/blob/master/core/src/main/resources/application.conf) and the [source-code](https://github.com/ennru/site-link-validator/blob/d8fa59afbe2228115868bb88d145e7578ae7e5fa/core/src/main/scala/net/runne/sitelinkvalidator/Main.scala#L68) I can't seem to find any such config.

Ill manually add the links for know, its a bit annoying but we only need to do it once and the dependencies don't get updated that often anyways.
