### ISSUE TITLE
Snapshot missing NOTICE file

### ISSUE THREAD

**Issue by Claudenw** [apache/incubator-pekko#329]
NOTICE file should be included in all jars, releases and snapshots.  It is currently missing from the SNAPSHOT jars.  The change should place the NOTICE in **ALL** snapshot jars as well a the release jars when they are built.

**Comment by pjfanning** [comment]
Can we use one issue? LICENSE in jar support also tries to support NOTICE files.

**Comment by pjfanning** [comment]
see #328 - I'm going to only comment on that other issue from now

**Comment by pjfanning** [comment]
closing in favour of doing all the work in #328
