### ISSUE TITLE
Set git tag protection rules on github.

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#342]
An upstream ticket for asfinfra has been created at https://issues.apache.org/jira/browse/INFRA-24637. I am also asking infra if its possible to set this permission manually for now (see https://the-asf.slack.com/archives/CBX4TSBQ8/p1684995671534989)

@pjfanning How do you feel about removing the `forked-from-akka` git tag? To me this seems out of place, and if we need to keep track of this we can always just document the exact git commit hash when the fork happened (which is probably more approachable for the types of people interested in this anyways).

**Comment by pjfanning** [comment]
I'd prefer to keep the 'forked-from-akka' tag. One of the Microsoft guys wanted something to mark the fork point. And tags avoid us having to add a documentation page that people may not be able to find.

If a malicious actor manages to interfere with the git tags, then maybe we can reconsider.

**Comment by mdedetrich** [comment]
My counter argument to this is that it does impact/break a lot of the sbt dynamic version from git tag tooling that has been built in various pekko modules. For example pekko-grpc had an issue with publishing/releasing because of git tag existing that doesn't follow the `v*.*.*` format and iirc I actually had to delete this tag to get things working.

Additionally, at least until git tag protection rules are setup it can be argued that using a git tag is not enough because they are mutable.

> If a malicious actor manages to interfere with the git tags, then maybe we can reconsider.
To me if we do setup a git tag protection rule its not going to cover `forked-from-akka`, it will just cover `v*.*.*`.

> And tags avoid us having to add a documentation page that people may not be able to find.
There is plenty of much higher stakes information in the documentation (i.e. legal/security/commercial related) and people being lazy to read documentation is to me quite a weak argument. Also tbh, the vast majority of people won't care about when exactly Pekko forked from Akka, the only people that will care about such a thing are the ones that care about legal/security/commercial matters and as mentioned before other info on this topic is in the docs.

@sam-byng Are you able to commend on this? Would it be enough for us to just document the exact git hash in pekko documentation (just like other legal/security/commercial related is documented) indicating when the fork happened rather than using a git tag?

**Comment by mdedetrich** [comment]
So asf infrajust responded and they said that they can set the git tag protection rules manually (see https://issues.apache.org/jira/browse/INFRA-24637?focusedCommentId=17726277&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17726277). The idea would be to add git tag protection rule that just covers the version pattern (i.e. `v*.*.*`). It wont have any existing effect on the `forked-from-akka` tag.

@pjfanning Are you happy with this. Should I start a discussion thread on it?

**Comment by pjfanning** [comment]
protecting the v tags makes sense - I wouldn't be against protecting all tags either - but the v tags are the most important

**Comment by mdedetrich** [comment]
Shall I just go ahead and create the ticket at asfinfra to do this?

**Comment by pjfanning** [comment]
> Shall I just go ahead and create the ticket at asfinfra to do this?

Sure - give them this link - https://incubator.apache.org/clutch/pekko.html

It has all our repos listed.

**Comment by mdedetrich** [comment]
Done, https://issues.apache.org/jira/browse/INFRA-24644

**Comment by mdedetrich** [comment]
So I can report that the manual setup of github tag protection is now working, although asfinfra needs to cleanup the implementation a bit. See https://issues.apache.org/jira/browse/INFRA-24644?focusedCommentId=17726630&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17726630 for more info
