### ISSUE TITLE
scala 2.12.18 and 2.13.11

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#344]
These should be released soon. See https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088 (which links to the 2.12.18 thread too).

I wouldn't block a Pekko release waiting for this but there is a reasonable argument to uptake these versions in Pekko build if they are released soon.

**Comment by He-Pin** [comment]
It's around the corner.
https://github.com/scala/scala-dev/issues/835 

I think we can wait:)

**Comment by pjfanning** [comment]
the release is complicated enough already - let's drop this from 1.0.0 consideration for now

**Comment by nvollmar** [comment]
I agree, unless there is a good reason I'd not upgrade to a new compiler release shortly before a release, too many unnecessary risks. Scala 3.3 should stay the exception.

**Comment by mkurz** [comment]
I would upgrade to 2.13.11 and 2.12.18 before cutting the release. These Scala 2.1x.xx versions are coordinated together with Scala 3.3.0 and should be released this week. These versions make sure everything works smoothly between these three versions e.g. the tasty thing gets adjusted, etc.
Also it seems sbt 1.9.0 is on hold until 2.12.18 is here, which will then be used as sbt's internal default Scala version.

**Comment by pjfanning** [comment]
I'm not sure - we are talking about the scala libs that we build with. Users of Pekko should use the latest Scala releases. Whether we use the absolutely latest Scala libs to build with is a different matter.

Normally I would say upgrade but we are in the middle of a release and I don't want to add risks to the release.

**Comment by pjfanning** [comment]
this is done
