### ISSUE TITLE
setup sbt plugin to allow publishing of signed jars to Apache Maven repository

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#351]
As part of releasing Pekko, we will need to run an sbt command to publish signed jars to Apache Maven repository

`sbt +publishSigned`

* [sbt-pgp](https://github.com/sbt/sbt-pgp)

Possibly other plugins could be used

**Comment by pjfanning** [comment]
@mdedetrich I'm fairly surprised that `sbt publishSigned` does not work. I would have thought that sbt-apache-sonatype would be loading sbt-pgp transitively. Anyway, adding sbt-pgp allows me at least to create signed jars locally. 

I'm currently playing with sbt-sonatype commands to try to prepare a release and worrying that I might accidentally get it to publish a release all the way to Maven Central.

**Comment by mdedetrich** [comment]
> @mdedetrich I'm fairly surprised that `sbt publishSigned` does not work. I would have thought that sbt-apache-sonatype would be loading sbt-pgp transitively. Anyway, adding sbt-pgp allows me at least to create signed jars locally.

By not working I guess you mean we are missing some dependency? If so adding sbt-pgp to sbt-apache-sonatype should solve the issue

> I'm currently playing with sbt-sonatype commands to try to prepare a release and worrying that I might accidentally get it to publish a release all the way to Maven Central.

One thing we need to take note of is sbt-sonatype by default does bundling, which means we may have to do something like https://github.com/sirthias/parboiled2/pull/452

**Comment by mdedetrich** [comment]
@pjfanning Release of sbt-apache-sonatype `v0.1.10` has been triggered which adds sbt-gpg as a dependency. Let me know if it solves your problem

**Comment by pjfanning** [comment]
@mdedetrich I don't mind adding sbt-pgp directly to each project but if you like we can do it indirectly via a new release of sbt-apache-sonatype.

I was able to generate a bundle in repository.apache.org using `sbt +publishSigned` and `sbt sonatypePrepare sonatypeBundleUpload`. 

This bundle is not closed so it will not yet be in staging. I could use `sbt sonatypeClose` but I think I prefer the idea of using the UI to close the bundle. We absolutely don't want a release manager to use the wrong sbt-sonatype command a do a full release before a vote has happened (ie `sbt sonatypeRelease` or `sbt sonatypeBundleRelease`).

**Comment by mdedetrich** [comment]
> @mdedetrich I don't mind adding sbt-pgp directly to each project but if you like we can do it indirectly via a new release of sbt-apache-sonatype.

Already done, check above comment

**Comment by pjfanning** [comment]
@mdedetrich could you have a look at https://repository.apache.org/content/groups/staging/org/apache/pekko/ ?

The contents of this look ok to me. I can drop this later today to avoid confusion.

**Comment by mdedetrich** [comment]
> @mdedetrich could you have a look at https://repository.apache.org/content/groups/staging/org/apache/pekko/ ?

The contents of this look ok to me. I can drop this later today to avoid confusion.

Can you try with `+publishSigned` to see that it works with all Scala versions?

**Comment by pjfanning** [comment]
@mdedetrich unfortunately, I'm hitting recurring issues building Scala 3 artifacts. The scaladoc job keeps just crashing out.

**Comment by mdedetrich** [comment]
Are you running `scaladoc` manually or this being run as part of `publishSigned`? I might have some idea of whats going on, hit similar issues with pekko-grpc Scala 3 migration.

**Comment by pjfanning** [comment]
scaladoc issues happen in publishSigned (needed for the javadoc jars)

**Comment by mdedetrich** [comment]
Okay I will look into it tomorrow/day after

**Comment by pjfanning** [comment]
@mdedetrich It seems to be failing at:

`(osgi / Compile / doc) Scaladoc generation failed`

I'm using a Mac (Monterey OS).

**Comment by mdedetrich** [comment]
@pjfanning 

Is this same problem as https://github.com/apache/incubator-pekko-grpc/actions/runs/5100731826/jobs/9169230377?

**Comment by pjfanning** [comment]
> @pjfanning
> 
> Is this same problem as https://github.com/apache/incubator-pekko-grpc/actions/runs/5100731826/jobs/9169230377?

Looks different to me

**Comment by pjfanning** [comment]
PR merged
