### ISSUE TITLE
publish v1.0.0 of docs

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#352]
See https://pekko.apache.org/docs/pekko/current/additional/osgi.html and its snapshot pekko version.

This will be confusing after the release.

I would suggest that we create a create a 1.0.0 branch and create a CI workflow that publishes the docs and scaladocs/javadocs but with `ThisBuild / version = "1.0.0"`. It needs to be a CI job because there are secrets needed to rsync the docs.

Having a branch means that we can fix issues and get the 1.0.0 docs republished.

We can modify the [.htaccess](https://github.com/apache/incubator-pekko-site/blob/main/src/main/paradox/.htaccess) file in pekko-site repo to map 'current' to 1.0.0.

**Comment by pjfanning** [comment]
https://pekko.apache.org/docs/pekko/current/ and https://pekko.apache.org/docs/pekko/1.0.0/ relate to 1.0.0 docs now.

Will need to update the CI job after the release to use the 1.0 branch. Or a git tag.

**Comment by mkurz** [comment]
Hi,
where can I find the api docs? Basically looking for Pekko version of
* https://doc.akka.io/japi/akka/2.6/ and
* https://doc.akka.io/japi/akka-http/10.2/
to replace 

https://github.com/playframework/playframework/blob/57af139ae5c531c8d7bb3e4c8523da85dc07dd9a/project/Docs.scala#L171-L174
Thanks!

**Comment by pjfanning** [comment]
@mkurz It's all linked here - https://pekko.apache.org/modules.html

**Comment by mdedetrich** [comment]
@pjfanning Is this still valid?
