### ISSUE TITLE
sbt-dependency-submission is submitting wrong versions of libraries

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#376]
Seems like sbt-dependency-submission is submitting the wrong versions of libraries to github, see upstream issue at https://github.com/scalacenter/sbt-dependency-submission/issues/109

**Comment by mdedetrich** [comment]
@pjfanning So scala-center figured out why this is happening, its because its reporting dependencies from sbt plugins as well, not just the run/compile time, see https://github.com/scalacenter/sbt-dependency-submission/issues/109#issuecomment-1586974291.

How should we configure this, i.e. should we be filtering out any sbt plugins on the premise that users of Pekko are not actually going to touch this code because its build related or should we report all potential security issues?

Regardless we should solve this by adding `libraryDependency += "com.fasterxml.jackson.core:jackson-databind:2.14.3"` to `project/plugins.sbt`. Ill make a PR now

**Comment by pjfanning** [comment]
It's possible that some of the sbt plugins may not work after being forced to use a newer Jackson version.
It might still be useful to find which ones break because we could see about upgrading that plugin or adding an issue for that plugin to upgrade its Jackson version.

In the end of the day, it is probably better for us if we only post up the lib dependencies and not worry so much about the sbt plugins that we use.

**Comment by mdedetrich** [comment]
> It's possible that some of the sbt plugins may not work after being forced to use a newer Jackson version.

I am creating a PR so lets see if this is an actual problem.

> In the end of the day, it is probably better for us if we only post up the lib dependencies and not worry so much about the sbt plugins that we use.

After thinking about this a bit more, it may still be problematic. i.e. people do run the builds locally on the machine and it is run in CI, so theoretically speaking security issues can still be abused.

**Comment by pjfanning** [comment]
Is there any way to get a dependency tree for all of the sbt plugins?
