### ISSUE TITLE
acknowledge use of Aeron code in Pekko

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#418]
See https://lists.apache.org/thread/mo611z4dpro1373r4f5pbgtlyjmhhtz9

These files:
* ./remote/src/test/java/org/apache/pekko/remote/artery/aeron/AeronStat.java
* ./remote/src/test/java/org/apache/pekko/remote/artery/RateReporter.java
* ./remote/src/main/java/org/apache/pekko/remote/artery/aeron/AeronErrorLog.java

possibly come from https://github.com/real-logic/aeron

**Comment by He-Pin** [comment]
So aeron is not beening used as a lib？

**Comment by pjfanning** [comment]
If you look at the 3 files in the description - they have `Copyright 2014-2017 Real Logic Ltd.`

This is what is getting us in trouble. We need to find out where these files came from and account for them in our LICENSE and NOTICE files.

Presumably, Lightbend copied these files to avoid having a jar depedendency.

**Comment by pjfanning** [comment]
#422 is merged
