### ISSUE TITLE
acknowledge licensing issues in AbstractNodeQueue

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#426]
https://github.com/apache/incubator-pekko/blob/532b7173c175c0c379074cb022e98f5002860c22/actor/src/main/java/org/apache/pekko/dispatch/AbstractNodeQueue.java#L21-L26

**Comment by pjfanning** [comment]
@jrudolph @mdedetrich  could the text in https://github.com/apache/incubator-pekko/pull/433 be adapted to include this too? AbstractNodeQueue does not have any inspiration from Andriy Plokhotnyuk's code but it is inspired by the MPSC code.

**Comment by mdedetrich** [comment]
> @jrudolph @mdedetrich could the text in #433 be adapted to include this too? AbstractNodeQueue does not have any inspiration from Andriy Plokhotnyuk's code but it is inspired by the MPSC code.

So I just had a look at the referenced code at https://www.1024cores.net/home/lock-free-algorithms/queues/non-intrusive-mpsc-node-based-queue and this does look like its a similar case, i.e. the code is in a different language (C) and is minimal compared to `AbstractNodeQueue`.

**Comment by mdedetrich** [comment]
Closing as completed, will re-open if more needs to be done.

**Comment by pjfanning** [comment]
@mdedetrich I think it is better if we modify the text from #433 to also mention 'AbstractNodeQueue.java'.

**Comment by pjfanning** [comment]
#434 merged
