### ISSUE TITLE
examine potential copy of scala-library code

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#428]
https://github.com/apache/incubator-pekko/blob/532b7173c175c0c379074cb022e98f5002860c22/actor/src/main/scala/org/apache/pekko/util/Helpers.scala#L117-L130

**Comment by mdedetrich** [comment]
So this is the original code https://github.com/scala/scala/blob/0842f23f6017f93160b115b8bf29ec5347cdbe94/src/library/scala/Predef.scala#L356-L361. Its the same case as me adding `Iterable.single`, i.e. https://github.com/apache/incubator-pekko/blob/d1a94323f5e968196edcadef1937010cb68a7219/actor/src/main/scala-2.12/org/apache/pekko/util/ccompat/package.scala#L80-L102

**Comment by pjfanning** [comment]
#436 merged
