### ISSUE TITLE
acknowledge use of riak code in ORSet

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#432]
https://github.com/apache/incubator-pekko/blob/60279703a49d0a678de44b3cf14f4904eff9def3/distributed-data/src/main/scala/org/apache/pekko/cluster/ddata/ORSet.scala#L277-L283

May need to also check the INRIA hosted PDFs.

Need to look at license implications of https://github.com/basho/riak_dt/blob/develop/src/riak_dt_orswot.erl

**Comment by mdedetrich** [comment]
> Need to look at license implications of https://github.com/basho/riak_dt/blob/develop/src/riak_dt_orswot.erl

Codebase is under Apache 2, see https://github.com/basho/riak_dt/blob/develop/LICENSE

**Comment by pjfanning** [comment]
even if the code is ASL, we still probably update the Pekko LICENSE and NOTICE to mention the Riak code
