### ISSUE TITLE
examine whether there is any Ben Manes' code in FrequencySketch

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#439]
https://lists.apache.org/thread/mo611z4dpro1373r4f5pbgtlyjmhhtz9 lists FrequencySketch twice. One relates to #438 

The other case is probably down to https://github.com/apache/incubator-pekko/blob/bd1af56fcead435cb3d730e759223dcb2b0fb4c6/actor/src/main/scala/org/apache/pekko/util/FrequencySketch.scala#L255-L256

**Comment by pjfanning** [comment]
@raboof @jrudolph I think the code is just inspired by Caffeine as opposed to any code being based directly on code lifted from Caffeine. If there is just inspiration, I expect that we don't need to mention it in the Pekko license.

**Comment by mdedetrich** [comment]
@pjfanning Given @ben-manes Comment I think the safest option would be to include a mention in LICENSE considering its small enough to be considered fair use (you can even link to his comment in there)

**Comment by pjfanning** [comment]
Thanks @ben-manes - I think it is better if we do acknowledge the use of code based on your Caffeine code base. I have created #446. If you see anything wrong in that PR, we will fix it.

**Comment by pjfanning** [comment]
#446 merged
