### ISSUE TITLE
Migrate multi-node-testkit to netty 4

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#462]
After drop the classical remoting which depends on netty 3, I think we can migrate the multi-node-testkit to netty 4

**Comment by pjfanning** [comment]
I guess that will need to be discussed on the dev mailing list. I have no objection to removing it but we haven't yet really discussed versioning strategy and the priorities for future development.

**Comment by pjfanning** [comment]
depends on https://github.com/apache/incubator-pekko/issues/41

**Comment by He-Pin** [comment]
I have a working local pr, will submit a pr tomorrow.
