### ISSUE TITLE
Potential note for migration guide for slf4j

### ISSUE THREAD

**Issue by bdoyle0182** [apache/incubator-pekko#490]
First, congratulations on the 1.0.0 milestone of the core repo! I'm playing around with migrations right now. Only issue I've faced is with my logging configuration. When starting my application I get this error.

```
[error] SLF4J: No SLF4J providers were found.
[error] SLF4J: Defaulting to no-operation (NOP) logger implementation
[error] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[error] SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
[error] SLF4J: Ignoring binding found at [***/ch.qos.logback/logback-classic/jars/logback-classic-1.2.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

I suspect this is probably from a transitive dependency updated in the pekko-slf4j module, maybe?

**But to solve the problem updating `ch.qos.logback` to 1.3.x series worked just fine.**

Possibly worth adding a note to migration guide. Maybe it's covered by one of the transitive dependencies that's listed as upgraded in 1.0.0, but having an explicit note about this might still be helpful.

**Comment by pjfanning** [comment]
@bdoyle0182 Could you check your own dependencies? pekko-slf4j has a dependency on slf4j-api 1.7.36

see https://mvnrepository.com/artifact/org.apache.pekko/pekko-slf4j_2.13/1.0.0

https://www.slf4j.org/codes.html#ignoredBindings seems to suggest that you should only see this issue if you have slf4j-api 2.x on your runtime classpath. Without a reproducible test case, I don't know how you could have that newer version of slf4j-api on your classpath.

If someone provides a reproducible scenario, we can look into it.

**Comment by bdoyle0182** [comment]
Yea at initial glance I only see `org.slf4j:slf4j-api:1.7.36` on my classpath. I'll try to dig deeper on this and compare to pre-migration state of repo

**Comment by bdoyle0182** [comment]
Okay the upgrade of `slf4j-api` is coming from my `swagger-pekko-http` snapshot from you. Apologies for opening an issue due to a snapshot, I just assumed it was from within pekko-slf4j.
