### ISSUE TITLE
multinode testkit change to netty4 has made it unreliable

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#547]
https://github.com/apache/incubator-pekko-http/actions/runs/5784088598/job/15674095366

The 'main' tests are using pekko jars that have been built off the 'main' branch of https://github.com/apache/incubator-pekko

fyi @kerr @mdedetrich

**Comment by He-Pin** [comment]
_Working on it, stay turn._

**Comment by He-Pin** [comment]
it works now https://github.com/apache/incubator-pekko-http/actions/runs/5788267905/job/15686902092

**Comment by He-Pin** [comment]
This is done by the https://github.com/apache/incubator-pekko-http/pull/297

**Comment by He-Pin** [comment]
It's fixed now.
