### ISSUE TITLE
Add CodeQL workflow for GitHub code scanning?

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#57]
Which will help reviewing.
demo: https://github.com/real-logic/agrona/pull/268
https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/

**Comment by pjfanning** [comment]
I don't think codeql supports Scala. Might be worth testing on a separate Github fork before we turn it on for Pekko.

**Comment by He-Pin** [comment]
Close for now, will reopen one day.

**Comment by gmethvin** [comment]
Snyk is a similar solution and supports Scala: https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-scala
