### ISSUE TITLE
scalafiddle is down and code snippets can be removed 

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#584]
The scalafiddle.io is down and there are some #scalafiddle code in the docs and should be removed.

**Comment by pjfanning** [comment]
Could you provide a link to a page of ours that has broken links?

**Comment by pjfanning** [comment]
@He-Pin can this be closed?

**Comment by pjfanning** [comment]
I'll close this. If there are still scalafiddle link, please reopen.
