### ISSUE TITLE
Deprecate `statefulMapConcat`

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#601]
Motivation:

As the `statefulMapConcat` not handing the `upstreamFinished` event, so when the stream is complete, the ongoing state ke
eped in the closure can be lost.

I suggest we annotate that in the scaladoc and deprecate the usage, and infavor the `statefulMap` 

As the tests in https://github.com/Kotlin/kotlinx.coroutines/pull/3868 shows and the origin Akka issue for `statefulMap: https://github.com/akka/akka/issues/31077

**Comment by pjfanning** [comment]
Is this something that can be done in Pekko 1.0.2? We should at least consider updating the Pekko 1.0 docs.

**Comment by He-Pin** [comment]
Can we deprecate things in the 1.0.x ?

**Comment by pjfanning** [comment]
> Can we deprecate things in the 1.0.x ?

yes, we can deprecate code in 1.0.x

something like

`@deprecated("This function has been replace by <otherFunctionName>", "1.0.2")` (the 2nd string is the version number)
