### ISSUE TITLE
Add Flow.onErrorComplete operator

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#624]
### Discussed in https://github.com/apache/incubator-pekko/discussions/623

<div type='discussions-op-text'>

<sup>Originally posted by **He-Pin** September  2, 2023</sup>
When we encounter an exception, sometime we may don't want the flow to result in an error but completes normally.

The implementation can be simple, but still cause some confusing.

I would like suggest to add a `onErrorComplete` operator which will complete the flow on some dedicated condition.

And better we have another `onErrorContiune` operator, which will keep the flow working but will need the operator before it to support this.</div>

**Comment by He-Pin** [comment]
@nvollmar That's a good idea.

**Comment by He-Pin** [comment]
@nvollmar I'm planning to handle this this weekend, onething I have in mind is we can have something like the `reactor-core`'s operator name, which is very easy to use and accessiable. so I would like to continue with `onErrorComplete` name, and I mostly using Javadsl.

What's your proposal is generic and great too.

**Comment by nvollmar** [comment]
I'm back home, so I'd be available for a review, just request me on the PR

**Comment by He-Pin** [comment]
In https://github.com/spring-projects/spring-framework/pull/31352 which split the usage of `onErrorResume`

**Comment by He-Pin** [comment]
refs:
