### ISSUE TITLE
Simplify Pekko typed actor implementation in Scala 3

### ISSUE THREAD

**Issue by eloots** [apache/incubator-pekko#660]
# Synopsis

Typed actor based application code in Pekko inherits the requirement from Akka that message adapters and message wrappers are needed for handling responses from other Actors. This adds boilerplate to the business logic and clutters up the application code.

The need to utilise message adapters stems from a limitation in the type inference capabilities of the Scala 2 compiler. The good news however is that, when coding a Pekko Typed actor based application in Scala 3, the clutter and boilerplate can be eliminated completely. This leads to actor code that is as lenient as an Pekko Classic implementation while preserving full type safeness (and which allows one to easily and safely refactor typed actor based code).

In the following paragraph, the principle is demonstrated with a simple example.

_My proposal is to, at a minimum, adapt the [section on message adapters](https://nightlies.apache.org/pekko/docs/pekko/main-snapshot/docs/typed/interaction-patterns.html#adapted-response) in the Pekko documentation, to explain the concept for Scala 3 users._

_In addition to that, reworking the example code in the documentation may be considered. This could be done by adding a Scala 3 tab next to the existing Java and Scala [2] tab._

## The base case: a Typed actor based application

We start from a simple actor based application with two actor, a `JobScheduler` and a `Worker` actor. The `JobScheduler` actor utilises the message adapter approach to process the `StartedJob` response message from the `Worker` actor.

The `Worker` code looks as follows:

```scala
object Worker:
  // My Commands
  sealed trait Command
  final case class StartJob(job: Job, replyTo: ActorRef[Response]) extends Command

  // My Responses
  sealed trait Response
  final case class StartedJob(job: Job) extends Response

  def apply(): Behavior[Command] =
    Behaviors.setup { case context =>
      Behaviors.receiveMessage { case StartJob(job, replyTo) =>
        context.log.info("Starting job {}", job)
        replyTo ! StartedJob(job)
        Behaviors.same
      }
    }
```

The `JobScheduler` actor looks as follows:

```scala
object JobScheduler:

  // My Commands
  sealed trait Command
  case object SendJob extends Command
  private final case class WorkerResponseWrapper(response: Worker.Response)
    extends Command                                                                 // (1)

  def apply(worker: ActorRef[Worker.Command]): Behavior[Command] =
    Behaviors.setup { context =>
      Behaviors.withTimers { timers =>
        val workerResponseWrapper: ActorRef[Worker.Response] =                      // (2)
          context.messageAdapter(response => WorkerResponseWrapper(response))       // (2)

        timers.startTimerAtFixedRate(SendJob, FiniteDuration(1, TimeUnit.SECONDS))

        Behaviors.receiveMessage {
          case SendJob =>
            worker ! Worker.StartJob(Job(UUID.randomUUID()), workerResponseWrapper) // (3)
            Behaviors.same
          case WorkerResponseWrapper(response) =>                                   // (4)
            response match {                                                        // (4)
              case Worker.StartedJob(job) =>                                        // (4)
                context.log.info("Worker responded {} started", job)
                Behaviors.same
            }
        }
      }
    }
```

We can observe the typical pattern:

- (1) The addition of a response message wrapper, marked `private` as to not pollute the actor's public protocol
- (2) The introduction of a message adapter (effectively an `ActorRef`)
- (3) Passing the message adapter `ActorRef` in the `replyTo` field of a message
- (4) Do a two level pattern match on the response, first to extract the actual, wrapped response, second to process the actual message

## Applying Scala 3 Union types to eliminate the clutter

The idea is to refactor actors that process responses so that their external protocol remains unchanged, but that have an "internal protocol" that is augmented with all the responses it needs to "understand". For this, the application of Scala 3's Union types play a crucial role.

To cut a long story short, here is the functionally equivalent in Scala 3 that obviates the need for message adapters (note that the `Worker` actor code is unmodified):

```scala
object JobScheduler:

  // My Commands
  sealed trait Command
  case object SendJob extends Command                                      // (1) The actor's protocol reduced to the bare essence
  
  private type CommandOrResponse = Command | Worker.Response               // (2) The actor's internal protocol extending the external with with the responses

  def apply(worker: ActorRef[Worker.Command]): Behavior[Command] =         // (3) The external protocol
    Behaviors.setup[CommandOrResponse] { context =>                        // (3) The internal (extended) protocol
      Behaviors.withTimers { timers =>

        timers.startTimerAtFixedRate(SendJob, FiniteDuration(1, TimeUnit.SECONDS))

        Behaviors.receiveMessage {
          case SendJob =>
            worker ! Worker.StartJob(Job(UUID.randomUUID()), context.self) // (4) No message adapter, just pass `self` as `replyTo`
            Behaviors.same
          case Worker.StartedJob(job) =>                                   // (5) Direct pattern match on the response
            context.log.info("Worker responded {} started", job)
            Behaviors.same
        }
      }
    }.narrow                                                               // (6) Needed because of the way `Behavior` is implemented
```

With this refactoring, the following can be observed:

- (1) The actor's protocol definition is reduced to its bare essence: it only lists the messages that are part of its internal protocol (one message in this example)
- (2) The actor's internal protocol which is the union of its external protocol and all the responses from other actors it needs to understand
- (3) Creation of the actor's `Behavior[Command]`: we assign a more general `Behavior[CommandOrResponse]`  to it which is fine as the latter can still be considered to be an instance of a more restricted behavior
- (4) Instead of passing a message adapter, we can directly pass the `self` `ActorRef` in the `replyTo` field of the sent message
- (5) No need to do a two-level pattern match
- (6) The need to call the `narrow` method on `Behavior[CommandOrResponse]` in order to make type checking pass. I will come back to this later.

A more elaborate example can be found in [this training course](https://github.com/lunatech-labs/lunatech-scala2-to-scala3-course) where the principle is applied in the exercise on Union types. To see the diffs between the before and after state, download the [lunatech-scala2-to-scala3-course-student.zip](https://github.com/lunatech-labs/lunatech-scala2-to-scala3-course/releases/download/3.0.8/lunatech-scala2-to-scala3-course-linearized.zip) artefact, unzip it and inspect the diffs on two actors:

```bash
$ unzip lunatech-scala2-to-scala3-course-linearized.zip

$ cd lunatech-scala2-to-scala3-course-linearized

$ git diff 8690131 04b3acd code/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
.
<elided>
.

$ git diff 8690131 04b3acd code/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
.
<elided>
.
```

## Conclusion 

If one can code up a Pekko typed actor based application in Scala 3, a significant simplification can be achieved by applying the demonstrated technique. In my opinion, the Pekko documentation would be enhanced if it explains this technique.

## The need to `narrow` the internal `Behavior[CommandOrResponse]` in Scala 3

The need doesn't stem from Scala 3 itself, but rather from the way `Behavior` and `ExtensibleBehavior` (which extends `Behavior`) are defined. Ideally, the latter should be defined as contravariant in its type parameter `T` (something that wasn't an option in Scala 2). [One has to wonder though if it wouldn't be possible to change that in Scala 2.13...]

**Comment by pjfanning** [comment]
Thanks @eloots for the detailed write up. Before changing our docs, my preference would be that we add a couple of tests that demo that the union behaviour works as you describe.

Would you consider submitting a PR that adds a test case (or 2) to the actor-typed-tests sub-module?

**Comment by eloots** [comment]
> Would you consider submitting a PR that adds a test case (or 2) to the actor-typed-tests sub-module?

Sure, I can have a look at that. At first glance, it seems that the current build definition doesn't yet have Scala 3 version specific source folders. Is this correct? The reason I ask is that I'd need to add Scala 3 specific test code to the project.

**Comment by pjfanning** [comment]
> > Would you consider submitting a PR that adds a test case (or 2) to the actor-typed-tests sub-module?
> 
> Sure, I can have a look at that. At first glance, it seems that the current build definition doesn't yet have Scala 3 version specific source folders. Is this correct? The reason I ask is that I'd need to add Scala 3 specific test code to the project.

Add a `src/test/scala-3` folder and I think sbt might handle this (by only including this source when scala3 is used). If this doesn't work, then you can add sbt settings to explicitly add it. Example of this at https://github.com/FasterXML/jackson-module-scala/blob/2.16/build.sbt#L93

**Comment by eloots** [comment]
@pjfanning 

I must be missing something obvious, but I'm encountering a problem with simply loading the project in sbt. I meet the prerequisites (I'm using Temurin-11.0.20.1 (which is the default JDK), have a JDK 8 installed, and have Graphviz installed).

This is what I get:

```
$ sbt
copying runtime jar...
[info] welcome to sbt 1.9.6 (Eclipse Adoptium Java 11.0.20.1)
[info] loading settings for project global-plugins from idea.sbt ...
[info] loading global plugins from /Users/ericloots/.sbt/1.0/plugins
[info] loading settings for project incubator-pekko-build from plugins.sbt ...
[info] loading project definition from /Users/ericloots/Trainingen/LBT/incubator-pekko/project
[info] Updating
https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
  No modified time in response
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-web:1.4.4 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-web;sbtVersion=1.0;scalaVersion=2.12:1.4.
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom
[error]   not found: /Users/ericloots/.ivy2/localcom.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
[error]   checksum format error: /Users/ericloots/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml.sha1
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-web;sbtVersion=1.0;scalaVersion=2.12:1.4.4
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom
[error]   not found: /Users/ericloots/.ivy2/localcom.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
[error]   checksum format error: /Users/ericloots/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml.sha1
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by pjfanning** [comment]
That file was probably accessible in the past. It is in my Coursier cache locally. As a short term workaround, would you be able to remove sbt-web from your copy of the plugins.sbt? It is probably only needed if you are building docs.

**Comment by eloots** [comment]
> Maybe you could delete /Users/ericloots/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web and see if the directory is properly fetched afterwards.

Yes; hadn't noticed that one. Fetching it after deleting it works and solves the problem. Just [successfully] ran the test suite in the `actor-typed-tests` sbt project.

**Comment by eloots** [comment]
> Would you consider submitting a PR that adds a test case (or 2) to the actor-typed-tests sub-module?

Opened #667

**Comment by pjfanning** [comment]
Closing because I think this is complete. Please reopen if there is more needed.
