### ISSUE TITLE
Update to protobuf has broken pekko-http

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko#703]
The PR at https://github.com/apache/incubator-pekko/pull/489 has broken pekko-http. The pekko-http nightly tests (which test against latest pekko snapshots) are failing with 

```
[error] ## Exception when compiling 378 sources to /home/runner/work/incubator-pekko-http/incubator-pekko-http/http-core/target/scala-2.12/classes
[error] scala.reflect.internal.FatalError: Error accessing /home/runner/.cache/coursier/v1/https/repository.apache.org/content/repositories/snapshots/org/apache/pekko/pekko-protobuf-v3_2.12/1.1.0-M0%2B101-1b1f5722-SNAPSHOT/pekko-protobuf-v3_2.12-1.1.0-M0%2B101-1b1f5722-SNAPSHOT.jar
```

See https://github.com/apache/incubator-pekko-http/actions/runs/6463888406/job/17547697513 as an example

@pjfanning

**Comment by pjfanning** [comment]
#489 is not about pekko-protobuf-v3 jar - it is about the old pekko-protobuf jar (note no `-v` in name).

The real issue is #685 - which I think is a bug in sbt-assembly.

**Comment by pjfanning** [comment]
https://github.com/sbt/sbt-assembly/issues/506

**Comment by mdedetrich** [comment]
Closing as duplicate to https://github.com/apache/incubator-pekko/issues/685
