### ISSUE TITLE
find alternative to unmaintained docker-client lib used in tests

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#806]
See https://github.com/spotify/docker-client

We are already having to force upgrades to many of its transitive dependencies - due to CVEs in those dependencies.

**Comment by laglangyue** [comment]
what do you think of docker-java https://github.com/docker-java/docker-java?
docker-client is no longer updated?

**Comment by samueleresca** [comment]
> what do you think of docker-java https://github.com/docker-java/docker-java? docker-client is no longer updated.

docker-java definetly looks a better option than docker-client:
- docker-client is deprecated
- docker-java seems maintained and more active

I'm not sure about the amount of work for doing the replacement, but I can give a try to docker-java in the next days / weekend
