### ISSUE TITLE
Spin loop in TLS Actor causes CPU to go to 100%

### ISSUE THREAD

**Issue by michaelarndt0423** [apache/incubator-pekko#842]
There was in issue in akka prior to 2.6.21 with CPU usage rising to 100% in certain circumstances. Ths complete description can be found in the akka project. In 2.6.21 a fix war backported but it does not seem to be part of pekko 1.0.1.

The link to the 2.6.21 release notes is a good starting point for further investigation: 

https://github.com/akka/akka/releases/tag/v2.6.21

**Comment by pjfanning** [comment]
@michaelarndt0423 are you seeing issues? We have https://github.com/apache/incubator-pekko/issues/442 and https://github.com/apache/incubator-pekko/pull/443. That PR is in pekko 1.0.0.

**Comment by michaelarndt0423** [comment]
Yes, we are currently facing this issue and it just looks identical to the problem we had with akka prior to 2.6.21 and the problem occurs only in services we have migrated from akka to pekko.
But if the fix is already part of the release we need to investigate further...

**Comment by pjfanning** [comment]
@michaelarndt0423 did you find the cause of the issue?

**Comment by michaelarndt0423** [comment]
@pjfanning No, not really. For me it was important that the backport is part of pekko. And as it has been part since ver 1.0.0 for me this issue is resolved.
