### ISSUE TITLE
Add pekko group in scala ecosystems of Discord

### ISSUE THREAD

**Issue by laglangyue** [apache/incubator-pekko#852]
there is an `akka group` in ecosystems of scala discord,so should add `pekko` so that more users can find `pekko` and talk about it,
surely in the early stages, there may not be many people in this group.
Even though my English is not very good, I am still on Discord to see what the Scala-Community is talking about,  I think it is very helpful for the spread and growth of the Pekko community

![image](https://github.com/apache/incubator-pekko/assets/35491928/6ae12393-970a-4a88-8e4b-47af74188ebb)

**Comment by pjfanning** [comment]
This is not a bug. Issue trackers are for bugs and product features.

**Comment by pjfanning** [comment]
Regarding the Scala Discord, you will need to talk the maintainers of that Discord channel to see if they will add a Pekko ecosystem.

**Comment by laglangyue** [comment]
> Regarding the Scala Discord, you will need to talk the maintainers of that Discord channel to see if they will add a Pekko ecosystem.

get it
