### ISSUE TITLE
GraphApply.scala.template deprecation misapplied

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#875]
https://github.com/apache/incubator-pekko/blob/16e587ded12d6ad83c66123c144b1dddfdebaad4/stream/src/main/boilerplate/org/apache/pekko/stream/scaladsl/GraphApply.scala.template#L36

Many create methods are created for this template. Each one gets its deprecation message but the numbers are incremented on each one - so the versions become nonsensical.

Oddly the '.6.' bit is retained but the other parts increment.

For example, one method ends up with

```
@deprecated("Use createGraph instead", "Akka 5.6.46")
```

**Comment by He-Pin** [comment]
![image](https://github.com/apache/incubator-pekko/assets/501740/d0c1a3a7-2975-4013-8ad5-4f472a6310c0)
