### ISSUE TITLE
Feature: Add pr link to git message automaticly by github

### ISSUE THREAD

**Issue by laglangyue** [apache/incubator-pekko#885]
like this sreenshot, which is from apache seatunnel
![image](https://github.com/apache/incubator-pekko/assets/35491928/b72d2d33-b3ff-496c-9ffc-926a2750db2e)

this link is not added by developer, and it's automatic, maybe by github.
this link can help us to trace history and reasons for changes and  obtain more information

**Comment by laglangyue** [comment]
![image](https://github.com/apache/incubator-pekko/assets/35491928/78283e8a-3e46-4ffc-90aa-c00a09150e95)

then add vcs.xml
```xml

<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
<component name="VcsDirectoryMappings">
  <mapping directory="$PROJECT_DIR$" vcs="Git"/>
</component>
<component name="IssueNavigationConfiguration">
  <option name="links">
    <list>
      <IssueNavigationLink>
        <option name="issueRegexp" value="#(\d+)"/>
        <option name="linkRegexp" value="https://github.com/apache/seatunnel/pull/$1"/>
      </IssueNavigationLink>
    </list>
  </option>
</component>
</project>
```

**Comment by He-Pin** [comment]
@mdedetrich @pjfanning ping, I can't access the setting tab.

**Comment by pjfanning** [comment]
You get the PR link if you squash merge.

**Comment by He-Pin** [comment]
I see, so I just need do a squash merge !

**Comment by mdedetrich** [comment]
Do note that the PR link in the git message is largely irrelevant because the github ui allows you to search by the commit hash and when you do this it will also provide the PR behind that commit hash.

**Comment by laglangyue** [comment]
> Do note that the PR link in the git message is largely irrelevant because the github ui allows you to search by the commit hash and when you do this it will also provide the PR behind that commit hash, even though I do admit that it is a nice touch.
> 
> Another thing to keep note of is that technically speaking according to ASF policy, github is a convenience and hence ASF projects shouldn't be tied to github. There is gitbox for that.

Infact, we won't actually add a link to the git message, we just added the `PR ID`.
such as this, the idea vcs plugin will translator the `PR ID` to a link，This is a convenient operation to review history. 
![image](https://github.com/apache/incubator-pekko/assets/35491928/9987add1-6fa3-4440-bbb1-badaa0036048)

as pjfanning said, use `squash merge` would get the pr-id

**Comment by mdedetrich** [comment]
I understand, my point is that even the PR link (i.e. the `#285` which you highlighted in the screenshot) is just a minor convenience if you copy the git hash of the commit and paste it in the search bar of the github repo, github will bring you to the original PR.
