### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by kw217** [apache/incubator-pekko#96]
Please document the CLA requirement, and explain how to fulfil it.

[CONTRIBUTING.md line 91](https://github.com/apache/incubator-pekko/blob/main/CONTRIBUTING.md?plain=1#L91) mentions "Sign the CLA", but I can't find the CLA. There should be a link to the CLA and details of how to sign it.

Is the required CLA https://www.apache.org/licenses/contributor-agreements.html ? If so, does that process have to be followed (i.e., send a signed PDF to Apache) or is there bot assistance?

Separately - how does the project validate that CLAs have been signed by all contributors?

Thanks.

**Comment by pjfanning** [comment]
https://www.apache.org/licenses/contributor-agreements.html is the right page (as you already attest)

* We do not insist on CLAs for minor changes.
* ASF members have access to check if you CLAs are registered

**Comment by kw217** [comment]
Thanks. Is it OK if I make a PR to add the above details to CONTRIBUTORS.md? My employer needs to know what CLA I would be signing.

**Comment by kw217** [comment]
Thanks! #97 is what I was after.
