### ISSUE TITLE
Feature request:Add Sink/Flow.forall operator

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#972]
Motivation:
Add `Sink.forall` which can be implemented with `fold / statefulMap`, just act as `Nil.forall)`

Both zio and fs2 has this method.

Result:
rich operators set, and It works as Java Stream 's `allMatch`.

**Comment by He-Pin** [comment]
@laglangyue Would you like to take care of this, thanks.

**Comment by pjfanning** [comment]
@laglangyue could you consider filling in an Apache committee form? For larger PRs, we require this. See the CONTRIBUTING.md page on this repo

**Comment by laglangyue** [comment]
> Would you like to take care of this, thanks.
willing to do this

> could you consider filling in an Apache committee form?
yeah，i will complete it as soon as possible

**Comment by laglangyue** [comment]
>> could you consider filling in an Apache committee form?

I had sended it to secretary@apache.org. it's my form
![image](https://github.com/apache/incubator-pekko/assets/35491928/a5b74cbf-a85a-42d3-964d-950dabab88fa)
