### ISSUE TITLE
Feature request:Add Sink.exists operator

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#973]
Motivation:
Add `Sink.exists` operator ,which can be implemented with `Sink.fold / statefulMap`.
Both zio and fs2 has this mehtod.

Result:
Rich operators set.

It should work as Java Stream's `anyMatch`.

**Comment by He-Pin** [comment]
@GreyPlane Would you like to take care about this?

**Comment by GreyPlane** [comment]
Thanks for the mention, I think it's OK, I'd like to pick this up maybe this weekend or earlier If I had time.
