### ISSUE TITLE
Fix publish doc on main

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#99]
https://github.com/apache/incubator-pekko/actions/runs/3898732569

Will look into it soon, on meeting

**Comment by pjfanning** [comment]
I've never used these features but in theory, we need to set up .asf.yaml to automatically publish the site.

https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-WebsitedeploymentserviceforGitrepositories

Pekko uses `sbt docs/paradox` to build the html but we somehow need to find the right .asf.yaml settings to publish that html.

**Comment by pjfanning** [comment]
It may also be possible to create a git repo for the web site - something like incubator-pekko-site,git. (`-site` is an ASF convention).

**Comment by kw217** [comment]
From https://infra.apache.org/project-site.html and https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-Staticwebsitecontentgeneration it looks to me like if we're not using Pelican or Jekyll, we're supposed to have our generator pipeline check in the updated docs to the `asf-site` branch of our repository, and have a simple `publish` rule in `.asf.yaml`. Feels a bit icky but workable.

**Comment by pjfanning** [comment]
https://github.com/apache/incubator-pekko-site

**Comment by kw217** [comment]
Nice! What does "once the site has been approved" refer to - is that just the review mentioned in step 6, or does it need to be approved by someone in ASF?

**Comment by pjfanning** [comment]
closing this in favour of https://github.com/apache/incubator-pekko/issues/149
