### ISSUE TITLE
add `Source#runHead` , `Source#runLast`,`Source#runIgnore`

### ISSUE THREAD

**Issue by laglangyue** [apache/incubator-pekko#996]
Sink has these operator, runWith(Sink....)  >>>> runHead/runLast/runIgnore
it will be useful to develop/debug/test flow

**Comment by laglangyue** [comment]
@He-Pin what do you think of them

**Comment by He-Pin** [comment]
@laglangyue Thanks , how about open one dedicated issues for each one of them, thank you. and IIRC, zio has `debug` operator. which is very easy to use, otherwise you will need something `alsoTo(Sink.printin)`

**Comment by laglangyue** [comment]
yes, I will close this and open one for them one by one.

> @laglangyue Thanks , how about open one dedicated issues for each one of them, thank you. and IIRC, zio has `debug` operator. which is very easy to use, otherwise you will need something `alsoTo(Sink.printin)`
