### ISSUE TITLE
add `source.runPrintln`

### ISSUE THREAD

**Issue by laglangyue** [apache/incubator-pekko#998]
we always use `runwith(Sink.println)`, Adding this operator will make it easier to use.
it is useful to develop/debug/test

**Comment by He-Pin** [comment]
I would like to say ,may be something like zoo's debug, where pekko now already has a .log operator.

**Comment by pjfanning** [comment]
I would definitely favour something that logs instead of something that writes directly to System.out.

**Comment by laglangyue** [comment]
> I would like to say ,may be something like zoo's debug, where pekko now already has a .log operator.

source.log, longger code than runWith
```
source.log("hello")
      .withAttributes(Attributes.logLevels(
        onElement = Attributes.LogLevels.Info
)).runWith(Sink.ignore)
```

> I would definitely favour something that logs (slf4j/log4j/logback) instead of something that writes directly to System.out.

when I write examples or develop a flow in ide,  I will print it to console. 
Especially for beginners, they may not even know the `source.log` operator.
I learned the Pekko operator and wrote many examples. `runPrintln` is a good method,
such as this:
![image](https://github.com/apache/incubator-pekko/assets/35491928/3e120d64-904d-4471-a51c-cdb595b41ad0)

**Comment by mdedetrich** [comment]
I an also not a fan of this addition. Printing using `println` is in general a pretty bad idea in production and `println` is hence typicly only used locally as a debugging tool.

To drive this point even further, there is a wartremover option in Scala that scans for `println` and fails compilation if it finds it.

**Comment by laglangyue** [comment]
Due to the lack of agreement from the main members of the community, and  scala3 developers can use extends methods.
I will close this issue.

**Comment by He-Pin** [comment]
There is a console logger，but you will need to remove it before production too.
